apiVersion: apps/v1
kind: Deployment
metadata:
  name: spfs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spfs-app
  template:
    metadata:
      labels:
        app: spfs-app
    spec:
      containers:
      - name: spfs-app
        image: spfs-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATA_MONGODB_URI
          value: "mongodb://mongo-0.mongo:27017,mongo-1.mongo:27017,mongo-2.mongo:27017/SPFS_DB?replicaSet=rs0&readPreference=secondaryPreferred"
        - name: SPRING_DATA_REDIS_HOST
          value: "redis"
        - name: SPRING_DATA_REDIS_PORT
          value: "6379"
