apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init-scripts
data:
  init-replica-set.sh: |
    #!/bin/bash
    echo "Waiting for mongo-0..."
    until mongosh --host mongo-0.mongo --eval "print(\"waited for connection\")"; do
      echo "Retrying..."
      sleep 2
    done

    echo "Initializing replica set..."
    mongosh --host mongo-0.mongo --eval '
      rs.initiate({
        _id: "rs0",
        members: [
          { _id: 0, host: "mongo-0.mongo:27017" },
          { _id: 1, host: "mongo-1.mongo:27017" },
          { _id: 2, host: "mongo-2.mongo:27017" }
        ]
      })
    '
