apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-init
spec:
  template:
    spec:
      containers:
      - name: mongo-init
        image: mongo:latest
        command: ["/bin/bash", "/scripts/init-replica-set.sh"]
        volumeMounts:
        - name: scripts
          mountPath: /scripts
      restartPolicy: OnFailure
      volumes:
      - name: scripts
        configMap:
          name: mongo-init-scripts
          defaultMode: 0777
